/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class answer_list {
    constructor() {
        this.id = undefined;
        this.uid_answer = undefined;
        this.uid_question = undefined;
        this.content = undefined;
        this.user_photoUrl = undefined;
        this.user_displayName = undefined;
        this.publishTime = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUid_answer(uid_answer) {
        this.uid_answer = uid_answer;
    }

    getUid_answer() {
        return this.uid_answer;
    }

    setUid_question(uid_question) {
        this.uid_question = uid_question;
    }

    getUid_question() {
        return this.uid_question;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setUser_photoUrl(user_photoUrl) {
        this.user_photoUrl = user_photoUrl;
    }

    getUser_photoUrl() {
        return this.user_photoUrl;
    }

    setUser_displayName(user_displayName) {
        this.user_displayName = user_displayName;
    }

    getUser_displayName() {
        return this.user_displayName;
    }

    setPublishTime(publishTime) {
        this.publishTime = publishTime;
    }

    getPublishTime() {
        return this.publishTime;
    }
}

answer_list.className = 'answer_list';

export {answer_list}