
/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class history_tips {
    constructor() {
        this.id = undefined;
        this.title = undefined;
        this.subtitle = undefined;
        this.content = undefined;
        this.photoUrl = undefined;
        this.label = undefined;
        this.scanTime = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setSubtitle(subtitle) {
        this.subtitle = subtitle;
    }

    getSubtitle() {
        return this.subtitle;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setPhotoUrl(photoUrl) {
        this.photoUrl = photoUrl;
    }

    getPhotoUrl() {
        return this.photoUrl;
    }

    setLabel(label) {
        this.label = label;
    }

    getLabel() {
        return this.label;
    }

    setScanTime(scanTime) {
        this.scanTime = scanTime;
    }

    getScanTime() {
        return this.scanTime;
    }
}

history_tips.className = 'history_tips';

export {history_tips}