/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class hotel {
    constructor() {
        this.id = undefined;
        this.hotelName = undefined;
        this.hotelPhoto = undefined;
        this.website = undefined;
        this.synopsis = undefined;
        this.prices = undefined;
        this.address = undefined;
        this.schedulePhone = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setHotelName(hotelName) {
        this.hotelName = hotelName;
    }

    getHotelName() {
        return this.hotelName;
    }

    setHotelPhoto(hotelPhoto) {
        this.hotelPhoto = hotelPhoto;
    }

    getHotelPhoto() {
        return this.hotelPhoto;
    }

    setWebsite(website) {
        this.website = website;
    }

    getWebsite() {
        return this.website;
    }

    setSynopsis(synopsis) {
        this.synopsis = synopsis;
    }

    getSynopsis() {
        return this.synopsis;
    }

    setPrices(prices) {
        this.prices = prices;
    }

    getPrices() {
        return this.prices;
    }

    setAddress(address) {
        this.address = address;
    }

    getAddress() {
        return this.address;
    }

    setSchedulePhone(schedulePhone) {
        this.schedulePhone = schedulePhone;
    }

    getSchedulePhone() {
        return this.schedulePhone;
    }
}

hotel.className = 'hotel';

export {hotel}