/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class question_list {
    constructor() {
        this.id = undefined;
        this.uid = undefined;
        this.title = undefined;
        this.content = undefined;
        this.label = undefined;
        this.publishTime = undefined;
        this.user_photoUrl = undefined;
        this.user_displayName = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setLabel(label) {
        this.label = label;
    }

    getLabel() {
        return this.label;
    }

    setPublishTime(publishTime) {
        this.publishTime = publishTime;
    }

    getPublishTime() {
        return this.publishTime;
    }

    setUser_photoUrl(user_photoUrl) {
        this.user_photoUrl = user_photoUrl;
    }

    getUser_photoUrl() {
        return this.user_photoUrl;
    }

    setUser_displayName(user_displayName) {
        this.user_displayName = user_displayName;
    }

    getUser_displayName() {
        return this.user_displayName;
    }
}

question_list.className = 'question_list';

export {question_list}