/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class search_history {
    constructor() {
        this.id = undefined;
        this.searchinfo = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setSearchinfo(searchinfo) {
        this.searchinfo = searchinfo;
    }

    getSearchinfo() {
        return this.searchinfo;
    }
}

search_history.className = 'search_history';

export {search_history}