/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class traveLogue {
    constructor() {
        this.id = undefined;
        this.title = undefined;
        this.content = undefined;
        this.photoUrl = undefined;
        this.publishTime = undefined;
        this.label = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setPhotoUrl(photoUrl) {
        this.photoUrl = photoUrl;
    }

    getPhotoUrl() {
        return this.photoUrl;
    }

    setPublishTime(publishTime) {
        this.publishTime = publishTime;
    }

    getPublishTime() {
        return this.publishTime;
    }

    setLabel(label) {
        this.label = label;
    }

    getLabel() {
        return this.label;
    }
}

traveLogue.className = 'traveLogue';

export {traveLogue}