/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class travel_tips {
    constructor() {
        this.id = undefined;
        this.title = undefined;
        this.subtitle = undefined;
        this.content = undefined;
        this.photoUrl = undefined;
        this.label = undefined;
        this.publishTime = undefined;
        this.userId = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setSubtitle(subtitle) {
        this.subtitle = subtitle;
    }

    getSubtitle() {
        return this.subtitle;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setPhotoUrl(photoUrl) {
        this.photoUrl = photoUrl;
    }

    getPhotoUrl() {
        return this.photoUrl;
    }

    setLabel(label) {
        this.label = label;
    }

    getLabel() {
        return this.label;
    }

    setPublishTime(publishTime) {
        this.publishTime = publishTime;
    }

    getPublishTime() {
        return this.publishTime;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }
}

travel_tips.className = 'travel_tips';

export {travel_tips}