/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class userInfo {
    constructor() {
        this.id = undefined;
        this.displayName = undefined;
        this.email = undefined;
        this.phoneNum = undefined;
        this.photoUrl = undefined;
        this.birthday = undefined;
        this.gender = 0;
        this.sign = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setDisplayName(displayName) {
        this.displayName = displayName;
    }

    getDisplayName() {
        return this.displayName;
    }

    setEmail(email) {
        this.email = email;
    }

    getEmail() {
        return this.email;
    }

    setPhoneNum(phoneNum) {
        this.phoneNum = phoneNum;
    }

    getPhoneNum() {
        return this.phoneNum;
    }

    setPhotoUrl(photoUrl) {
        this.photoUrl = photoUrl;
    }

    getPhotoUrl() {
        return this.photoUrl;
    }

    setBirthday(birthday) {
        this.birthday = birthday;
    }

    getBirthday() {
        return this.birthday;
    }

    setGender(gender) {
        this.gender = gender;
    }

    getGender() {
        return this.gender;
    }

    setSign(sign) {
        this.sign = sign;
    }

    getSign() {
        return this.sign;
    }
}

userInfo.className = 'userInfo';

export {userInfo}